from __future__ import annotations

from identity_access.infrastructure.persistence.api_key_repository import (
    create_api_key,
    get_api_key,
    list_api_keys,
    revoke_api_key,
    update_api_key,
    validate_api_key,
)
from identity_access.infrastructure.persistence.common import (
    DisabledUserException,
    auth_database_target,
    build_menu_tree,
    connect,
    ensure_auth_schema,
    ensure_default_admin,
    ensure_default_rbac,
    ensure_menu_schema,
    now_iso,
    normalize_username,
    require_auth_ready,
    row_to_api_key,
    row_to_menu,
)
from identity_access.infrastructure.persistence.rbac_repository import (
    bound_roles_for_menu_keys,
    collect_menu_subtree,
    create_menu,
    create_role,
    delete_menu,
    delete_role,
    ensure_menu_not_bound,
    ensure_menu_structure_not_changed_when_bound,
    ensure_permission_definition,
    list_menus,
    list_permissions,
    list_roles,
    menu_tree_rows,
    rebuild_all_role_permissions,
    resolve_role_menu_selection,
    sync_role_access,
    update_menu,
    update_role,
    update_role_menus,
    user_access_payload,
    validate_menu_payload,
)
from identity_access.infrastructure.persistence.user_repository import (
    authenticate_platform_admin,
    authenticate_user,
    create_user,
    ensure_last_superuser_survives,
    list_platform_users,
    list_users,
    platform_user_by_username,
    public_user,
    resolve_role_ids,
    set_user_active,
    sync_user_roles,
    update_own_profile,
    update_user,
    user_by_username,
)
