from __future__ import annotations

from typing import Any, Protocol


class AIApplicationsRepository(Protocol):
    def __getattr__(self, name: str) -> Any: ...
    def require_ai_applications_schema(self, *args: Any, **kwargs: Any) -> Any: ...
    def require_ai_agent_schema(self, *args: Any, **kwargs: Any) -> Any: ...
    def require_prompt_runtime_trace_detail_schema(self, *args: Any, **kwargs: Any) -> Any: ...

