CREATE TABLE IF NOT EXISTS audit_system_logs (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    event_time TEXT NOT NULL,
    request_id TEXT NOT NULL DEFAULT '',
    correlation_id TEXT NOT NULL DEFAULT '',
    event_action TEXT NOT NULL DEFAULT '',
    event_outcome TEXT NOT NULL DEFAULT 'success',
    severity TEXT NOT NULL DEFAULT 'info',
    source_module TEXT NOT NULL DEFAULT '',
    actor_user_id BIGINT DEFAULT NULL,
    actor_name TEXT NOT NULL DEFAULT '',
    actor_type TEXT NOT NULL DEFAULT '',
    owner_user_id BIGINT DEFAULT NULL,
    owner_department_id BIGINT DEFAULT NULL,
    owner_department_path TEXT NOT NULL DEFAULT '',
    client_ip TEXT NOT NULL DEFAULT '',
    user_agent TEXT NOT NULL DEFAULT '',
    summary TEXT NOT NULL DEFAULT '',
    detail_json TEXT NOT NULL DEFAULT '{}',
    lock_version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    create_time TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creator TEXT NOT NULL DEFAULT '',
    creator_id BIGINT DEFAULT NULL,
    update_time TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    editor TEXT NOT NULL DEFAULT '',
    editor_id BIGINT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS audit_operation_logs (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    event_time TEXT NOT NULL,
    request_id TEXT NOT NULL DEFAULT '',
    correlation_id TEXT NOT NULL DEFAULT '',
    event_action TEXT NOT NULL DEFAULT '',
    event_outcome TEXT NOT NULL DEFAULT 'success',
    severity TEXT NOT NULL DEFAULT 'info',
    source_module TEXT NOT NULL DEFAULT '',
    actor_user_id BIGINT DEFAULT NULL,
    actor_name TEXT NOT NULL DEFAULT '',
    actor_type TEXT NOT NULL DEFAULT '',
    owner_user_id BIGINT DEFAULT NULL,
    owner_department_id BIGINT DEFAULT NULL,
    owner_department_path TEXT NOT NULL DEFAULT '',
    target_owner_user_id BIGINT DEFAULT NULL,
    target_owner_department_id BIGINT DEFAULT NULL,
    client_ip TEXT NOT NULL DEFAULT '',
    user_agent TEXT NOT NULL DEFAULT '',
    operation_type TEXT NOT NULL DEFAULT '',
    resource_type TEXT NOT NULL DEFAULT '',
    resource_id TEXT NOT NULL DEFAULT '',
    resource_name TEXT NOT NULL DEFAULT '',
    risk_level TEXT NOT NULL DEFAULT '',
    summary TEXT NOT NULL DEFAULT '',
    before_json TEXT NOT NULL DEFAULT '{}',
    after_json TEXT NOT NULL DEFAULT '{}',
    diff_json TEXT NOT NULL DEFAULT '{}',
    detail_json TEXT NOT NULL DEFAULT '{}',
    error_code TEXT NOT NULL DEFAULT '',
    error_message TEXT NOT NULL DEFAULT '',
    lock_version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    create_time TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creator TEXT NOT NULL DEFAULT '',
    creator_id BIGINT DEFAULT NULL,
    update_time TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    editor TEXT NOT NULL DEFAULT '',
    editor_id BIGINT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS audit_api_logs (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    event_time TEXT NOT NULL,
    request_id TEXT NOT NULL DEFAULT '',
    correlation_id TEXT NOT NULL DEFAULT '',
    event_action TEXT NOT NULL DEFAULT '',
    event_outcome TEXT NOT NULL DEFAULT 'success',
    severity TEXT NOT NULL DEFAULT 'info',
    source_module TEXT NOT NULL DEFAULT '',
    actor_user_id BIGINT DEFAULT NULL,
    actor_name TEXT NOT NULL DEFAULT '',
    actor_type TEXT NOT NULL DEFAULT '',
    owner_user_id BIGINT DEFAULT NULL,
    owner_department_id BIGINT DEFAULT NULL,
    owner_department_path TEXT NOT NULL DEFAULT '',
    client_ip TEXT NOT NULL DEFAULT '',
    user_agent TEXT NOT NULL DEFAULT '',
    request_method TEXT NOT NULL DEFAULT '',
    request_path TEXT NOT NULL DEFAULT '',
    route_name TEXT NOT NULL DEFAULT '',
    query_summary_json TEXT NOT NULL DEFAULT '{}',
    status_code BIGINT NOT NULL DEFAULT 0,
    business_code TEXT NOT NULL DEFAULT '',
    success BOOLEAN NOT NULL DEFAULT TRUE,
    duration_ms BIGINT NOT NULL DEFAULT 0,
    request_size_bytes BIGINT NOT NULL DEFAULT 0,
    response_size_bytes BIGINT NOT NULL DEFAULT 0,
    referer TEXT NOT NULL DEFAULT '',
    summary TEXT NOT NULL DEFAULT '',
    detail_json TEXT NOT NULL DEFAULT '{}',
    error_message TEXT NOT NULL DEFAULT '',
    lock_version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    create_time TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creator TEXT NOT NULL DEFAULT '',
    creator_id BIGINT DEFAULT NULL,
    update_time TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    editor TEXT NOT NULL DEFAULT '',
    editor_id BIGINT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS audit_sql_logs (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    event_time TEXT NOT NULL,
    request_id TEXT NOT NULL DEFAULT '',
    correlation_id TEXT NOT NULL DEFAULT '',
    event_action TEXT NOT NULL DEFAULT '',
    event_outcome TEXT NOT NULL DEFAULT 'success',
    severity TEXT NOT NULL DEFAULT 'info',
    source_module TEXT NOT NULL DEFAULT '',
    actor_user_id BIGINT DEFAULT NULL,
    actor_name TEXT NOT NULL DEFAULT '',
    actor_type TEXT NOT NULL DEFAULT '',
    owner_user_id BIGINT DEFAULT NULL,
    owner_department_id BIGINT DEFAULT NULL,
    owner_department_path TEXT NOT NULL DEFAULT '',
    client_ip TEXT NOT NULL DEFAULT '',
    user_agent TEXT NOT NULL DEFAULT '',
    database_backend TEXT NOT NULL DEFAULT '',
    statement_type TEXT NOT NULL DEFAULT '',
    table_names_json TEXT NOT NULL DEFAULT '[]',
    sql_fingerprint TEXT NOT NULL DEFAULT '',
    sql_template TEXT NOT NULL DEFAULT '',
    duration_ms BIGINT NOT NULL DEFAULT 0,
    row_count BIGINT DEFAULT NULL,
    success BOOLEAN NOT NULL DEFAULT TRUE,
    summary TEXT NOT NULL DEFAULT '',
    detail_json TEXT NOT NULL DEFAULT '{}',
    error_code TEXT NOT NULL DEFAULT '',
    error_message TEXT NOT NULL DEFAULT '',
    lock_version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    create_time TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creator TEXT NOT NULL DEFAULT '',
    creator_id BIGINT DEFAULT NULL,
    update_time TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    editor TEXT NOT NULL DEFAULT '',
    editor_id BIGINT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS audit_visitor_logs (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    event_time TEXT NOT NULL,
    request_id TEXT NOT NULL DEFAULT '',
    correlation_id TEXT NOT NULL DEFAULT '',
    event_action TEXT NOT NULL DEFAULT '',
    event_outcome TEXT NOT NULL DEFAULT 'success',
    severity TEXT NOT NULL DEFAULT 'info',
    source_module TEXT NOT NULL DEFAULT '',
    actor_user_id BIGINT DEFAULT NULL,
    actor_name TEXT NOT NULL DEFAULT '',
    actor_type TEXT NOT NULL DEFAULT '',
    owner_user_id BIGINT DEFAULT NULL,
    owner_department_id BIGINT DEFAULT NULL,
    owner_department_path TEXT NOT NULL DEFAULT '',
    visitor_id TEXT NOT NULL DEFAULT '',
    session_id_hash TEXT NOT NULL DEFAULT '',
    client_ip TEXT NOT NULL DEFAULT '',
    ip_hash TEXT NOT NULL DEFAULT '',
    user_agent TEXT NOT NULL DEFAULT '',
    device_type TEXT NOT NULL DEFAULT '',
    browser TEXT NOT NULL DEFAULT '',
    os TEXT NOT NULL DEFAULT '',
    referer TEXT NOT NULL DEFAULT '',
    entry_path TEXT NOT NULL DEFAULT '',
    failure_reason TEXT NOT NULL DEFAULT '',
    geo_country TEXT NOT NULL DEFAULT '',
    geo_region TEXT NOT NULL DEFAULT '',
    geo_city TEXT NOT NULL DEFAULT '',
    summary TEXT NOT NULL DEFAULT '',
    detail_json TEXT NOT NULL DEFAULT '{}',
    lock_version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    create_time TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creator TEXT NOT NULL DEFAULT '',
    creator_id BIGINT DEFAULT NULL,
    update_time TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    editor TEXT NOT NULL DEFAULT '',
    editor_id BIGINT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS audit_logging_settings (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    api_log_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    operation_log_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    sql_log_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    visitor_log_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    system_log_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    slow_sql_threshold_ms BIGINT NOT NULL DEFAULT 500,
    queue_max_size BIGINT NOT NULL DEFAULT 10000,
    batch_size BIGINT NOT NULL DEFAULT 100,
    flush_interval_ms BIGINT NOT NULL DEFAULT 1000,
    plaintext_ip_retention_days BIGINT NOT NULL DEFAULT 30,
    log_retention_days BIGINT NOT NULL DEFAULT 180,
    include_request_headers BOOLEAN NOT NULL DEFAULT FALSE,
    include_response_body BOOLEAN NOT NULL DEFAULT FALSE,
    external_sink_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    external_sink_type TEXT NOT NULL DEFAULT '',
    config_json TEXT NOT NULL DEFAULT '{}',
    lock_version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    create_time TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creator TEXT NOT NULL DEFAULT '',
    creator_id BIGINT DEFAULT NULL,
    update_time TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    editor TEXT NOT NULL DEFAULT '',
    editor_id BIGINT DEFAULT NULL,
    UNIQUE (tenant_id)
);

CREATE INDEX IF NOT EXISTS idx_audit_system_logs_tenant_time ON audit_system_logs(tenant_id, event_time);
CREATE INDEX IF NOT EXISTS idx_audit_operation_logs_tenant_time ON audit_operation_logs(tenant_id, event_time);
CREATE INDEX IF NOT EXISTS idx_audit_api_logs_tenant_time ON audit_api_logs(tenant_id, event_time);
CREATE INDEX IF NOT EXISTS idx_audit_sql_logs_tenant_time ON audit_sql_logs(tenant_id, event_time);
CREATE INDEX IF NOT EXISTS idx_audit_visitor_logs_tenant_time ON audit_visitor_logs(tenant_id, event_time);

