CREATE TABLE IF NOT EXISTS audit_system_logs (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    event_time VARCHAR(64) NOT NULL,
    request_id VARCHAR(191) NOT NULL DEFAULT '',
    correlation_id VARCHAR(191) NOT NULL DEFAULT '',
    event_action VARCHAR(191) NOT NULL DEFAULT '',
    event_outcome VARCHAR(32) NOT NULL DEFAULT 'success',
    severity VARCHAR(32) NOT NULL DEFAULT 'info',
    source_module VARCHAR(191) NOT NULL DEFAULT '',
    actor_user_id BIGINT DEFAULT NULL,
    actor_name VARCHAR(191) NOT NULL DEFAULT '',
    actor_type VARCHAR(64) NOT NULL DEFAULT '',
    owner_user_id BIGINT DEFAULT NULL,
    owner_department_id BIGINT DEFAULT NULL,
    owner_department_path VARCHAR(512) NOT NULL DEFAULT '',
    client_ip VARCHAR(64) NOT NULL DEFAULT '',
    user_agent LONGTEXT NOT NULL,
    summary LONGTEXT NOT NULL,
    detail_json LONGTEXT NOT NULL,
    lock_version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    create_time VARCHAR(64) NOT NULL DEFAULT '',
    creator VARCHAR(191) NOT NULL DEFAULT '',
    creator_id BIGINT DEFAULT NULL,
    update_time VARCHAR(64) NOT NULL DEFAULT '',
    editor VARCHAR(191) NOT NULL DEFAULT '',
    editor_id BIGINT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS audit_operation_logs (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    event_time VARCHAR(64) NOT NULL,
    request_id VARCHAR(191) NOT NULL DEFAULT '',
    correlation_id VARCHAR(191) NOT NULL DEFAULT '',
    event_action VARCHAR(191) NOT NULL DEFAULT '',
    event_outcome VARCHAR(32) NOT NULL DEFAULT 'success',
    severity VARCHAR(32) NOT NULL DEFAULT 'info',
    source_module VARCHAR(191) NOT NULL DEFAULT '',
    actor_user_id BIGINT DEFAULT NULL,
    actor_name VARCHAR(191) NOT NULL DEFAULT '',
    actor_type VARCHAR(64) NOT NULL DEFAULT '',
    owner_user_id BIGINT DEFAULT NULL,
    owner_department_id BIGINT DEFAULT NULL,
    owner_department_path VARCHAR(512) NOT NULL DEFAULT '',
    target_owner_user_id BIGINT DEFAULT NULL,
    target_owner_department_id BIGINT DEFAULT NULL,
    client_ip VARCHAR(64) NOT NULL DEFAULT '',
    user_agent LONGTEXT NOT NULL,
    operation_type VARCHAR(64) NOT NULL DEFAULT '',
    resource_type VARCHAR(191) NOT NULL DEFAULT '',
    resource_id VARCHAR(191) NOT NULL DEFAULT '',
    resource_name VARCHAR(255) NOT NULL DEFAULT '',
    risk_level VARCHAR(32) NOT NULL DEFAULT '',
    summary LONGTEXT NOT NULL,
    before_json LONGTEXT NOT NULL,
    after_json LONGTEXT NOT NULL,
    diff_json LONGTEXT NOT NULL,
    detail_json LONGTEXT NOT NULL,
    error_code VARCHAR(191) NOT NULL DEFAULT '',
    error_message LONGTEXT NOT NULL,
    lock_version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    create_time VARCHAR(64) NOT NULL DEFAULT '',
    creator VARCHAR(191) NOT NULL DEFAULT '',
    creator_id BIGINT DEFAULT NULL,
    update_time VARCHAR(64) NOT NULL DEFAULT '',
    editor VARCHAR(191) NOT NULL DEFAULT '',
    editor_id BIGINT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS audit_api_logs (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    event_time VARCHAR(64) NOT NULL,
    request_id VARCHAR(191) NOT NULL DEFAULT '',
    correlation_id VARCHAR(191) NOT NULL DEFAULT '',
    event_action VARCHAR(191) NOT NULL DEFAULT '',
    event_outcome VARCHAR(32) NOT NULL DEFAULT 'success',
    severity VARCHAR(32) NOT NULL DEFAULT 'info',
    source_module VARCHAR(191) NOT NULL DEFAULT '',
    actor_user_id BIGINT DEFAULT NULL,
    actor_name VARCHAR(191) NOT NULL DEFAULT '',
    actor_type VARCHAR(64) NOT NULL DEFAULT '',
    owner_user_id BIGINT DEFAULT NULL,
    owner_department_id BIGINT DEFAULT NULL,
    owner_department_path VARCHAR(512) NOT NULL DEFAULT '',
    client_ip VARCHAR(64) NOT NULL DEFAULT '',
    user_agent LONGTEXT NOT NULL,
    request_method VARCHAR(32) NOT NULL DEFAULT '',
    request_path VARCHAR(1024) NOT NULL DEFAULT '',
    route_name VARCHAR(191) NOT NULL DEFAULT '',
    query_summary_json LONGTEXT NOT NULL,
    status_code BIGINT NOT NULL DEFAULT 0,
    business_code VARCHAR(191) NOT NULL DEFAULT '',
    success BOOLEAN NOT NULL DEFAULT TRUE,
    duration_ms BIGINT NOT NULL DEFAULT 0,
    request_size_bytes BIGINT NOT NULL DEFAULT 0,
    response_size_bytes BIGINT NOT NULL DEFAULT 0,
    referer VARCHAR(1024) NOT NULL DEFAULT '',
    summary LONGTEXT NOT NULL,
    detail_json LONGTEXT NOT NULL,
    error_message LONGTEXT NOT NULL,
    lock_version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    create_time VARCHAR(64) NOT NULL DEFAULT '',
    creator VARCHAR(191) NOT NULL DEFAULT '',
    creator_id BIGINT DEFAULT NULL,
    update_time VARCHAR(64) NOT NULL DEFAULT '',
    editor VARCHAR(191) NOT NULL DEFAULT '',
    editor_id BIGINT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS audit_sql_logs (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    event_time VARCHAR(64) NOT NULL,
    request_id VARCHAR(191) NOT NULL DEFAULT '',
    correlation_id VARCHAR(191) NOT NULL DEFAULT '',
    event_action VARCHAR(191) NOT NULL DEFAULT '',
    event_outcome VARCHAR(32) NOT NULL DEFAULT 'success',
    severity VARCHAR(32) NOT NULL DEFAULT 'info',
    source_module VARCHAR(191) NOT NULL DEFAULT '',
    actor_user_id BIGINT DEFAULT NULL,
    actor_name VARCHAR(191) NOT NULL DEFAULT '',
    actor_type VARCHAR(64) NOT NULL DEFAULT '',
    owner_user_id BIGINT DEFAULT NULL,
    owner_department_id BIGINT DEFAULT NULL,
    owner_department_path VARCHAR(512) NOT NULL DEFAULT '',
    client_ip VARCHAR(64) NOT NULL DEFAULT '',
    user_agent LONGTEXT NOT NULL,
    database_backend VARCHAR(64) NOT NULL DEFAULT '',
    statement_type VARCHAR(64) NOT NULL DEFAULT '',
    table_names_json LONGTEXT NOT NULL,
    sql_fingerprint VARCHAR(191) NOT NULL DEFAULT '',
    sql_template LONGTEXT NOT NULL,
    duration_ms BIGINT NOT NULL DEFAULT 0,
    row_count BIGINT DEFAULT NULL,
    success BOOLEAN NOT NULL DEFAULT TRUE,
    summary LONGTEXT NOT NULL,
    detail_json LONGTEXT NOT NULL,
    error_code VARCHAR(191) NOT NULL DEFAULT '',
    error_message LONGTEXT NOT NULL,
    lock_version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    create_time VARCHAR(64) NOT NULL DEFAULT '',
    creator VARCHAR(191) NOT NULL DEFAULT '',
    creator_id BIGINT DEFAULT NULL,
    update_time VARCHAR(64) NOT NULL DEFAULT '',
    editor VARCHAR(191) NOT NULL DEFAULT '',
    editor_id BIGINT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS audit_visitor_logs (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    event_time VARCHAR(64) NOT NULL,
    request_id VARCHAR(191) NOT NULL DEFAULT '',
    correlation_id VARCHAR(191) NOT NULL DEFAULT '',
    event_action VARCHAR(191) NOT NULL DEFAULT '',
    event_outcome VARCHAR(32) NOT NULL DEFAULT 'success',
    severity VARCHAR(32) NOT NULL DEFAULT 'info',
    source_module VARCHAR(191) NOT NULL DEFAULT '',
    actor_user_id BIGINT DEFAULT NULL,
    actor_name VARCHAR(191) NOT NULL DEFAULT '',
    actor_type VARCHAR(64) NOT NULL DEFAULT '',
    owner_user_id BIGINT DEFAULT NULL,
    owner_department_id BIGINT DEFAULT NULL,
    owner_department_path VARCHAR(512) NOT NULL DEFAULT '',
    client_ip VARCHAR(64) NOT NULL DEFAULT '',
    user_agent LONGTEXT NOT NULL,
    visitor_id VARCHAR(191) NOT NULL DEFAULT '',
    session_id_hash VARCHAR(191) NOT NULL DEFAULT '',
    ip_hash VARCHAR(191) NOT NULL DEFAULT '',
    device_type VARCHAR(64) NOT NULL DEFAULT '',
    browser VARCHAR(191) NOT NULL DEFAULT '',
    os VARCHAR(191) NOT NULL DEFAULT '',
    referer VARCHAR(1024) NOT NULL DEFAULT '',
    entry_path VARCHAR(1024) NOT NULL DEFAULT '',
    failure_reason VARCHAR(255) NOT NULL DEFAULT '',
    geo_country VARCHAR(64) NOT NULL DEFAULT '',
    geo_region VARCHAR(191) NOT NULL DEFAULT '',
    geo_city VARCHAR(191) NOT NULL DEFAULT '',
    summary LONGTEXT NOT NULL,
    detail_json LONGTEXT NOT NULL,
    lock_version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    create_time VARCHAR(64) NOT NULL DEFAULT '',
    creator VARCHAR(191) NOT NULL DEFAULT '',
    creator_id BIGINT DEFAULT NULL,
    update_time VARCHAR(64) NOT NULL DEFAULT '',
    editor VARCHAR(191) NOT NULL DEFAULT '',
    editor_id BIGINT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS audit_logging_settings (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    api_log_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    operation_log_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    sql_log_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    visitor_log_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    system_log_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    slow_sql_threshold_ms BIGINT NOT NULL DEFAULT 500,
    queue_max_size BIGINT NOT NULL DEFAULT 10000,
    batch_size BIGINT NOT NULL DEFAULT 100,
    flush_interval_ms BIGINT NOT NULL DEFAULT 1000,
    plaintext_ip_retention_days BIGINT NOT NULL DEFAULT 30,
    log_retention_days BIGINT NOT NULL DEFAULT 180,
    include_request_headers BOOLEAN NOT NULL DEFAULT FALSE,
    include_response_body BOOLEAN NOT NULL DEFAULT FALSE,
    external_sink_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    external_sink_type VARCHAR(64) NOT NULL DEFAULT '',
    config_json LONGTEXT NOT NULL,
    lock_version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    create_time VARCHAR(64) NOT NULL DEFAULT '',
    creator VARCHAR(191) NOT NULL DEFAULT '',
    creator_id BIGINT DEFAULT NULL,
    update_time VARCHAR(64) NOT NULL DEFAULT '',
    editor VARCHAR(191) NOT NULL DEFAULT '',
    editor_id BIGINT DEFAULT NULL,
    UNIQUE (tenant_id)
);

CREATE INDEX IF NOT EXISTS idx_audit_system_logs_tenant_time ON audit_system_logs(tenant_id, event_time);
CREATE INDEX IF NOT EXISTS idx_audit_operation_logs_tenant_time ON audit_operation_logs(tenant_id, event_time);
CREATE INDEX IF NOT EXISTS idx_audit_api_logs_tenant_time ON audit_api_logs(tenant_id, event_time);
CREATE INDEX IF NOT EXISTS idx_audit_sql_logs_tenant_time ON audit_sql_logs(tenant_id, event_time);
CREATE INDEX IF NOT EXISTS idx_audit_visitor_logs_tenant_time ON audit_visitor_logs(tenant_id, event_time);
