import { renderIcon } from '@/utils/index';
import {
  ApiOutlined,
  ApartmentOutlined,
  AppstoreOutlined,
  BgColorsOutlined,
  BellOutlined,
  BookOutlined,
  BugOutlined,
  BuildOutlined,
  CalendarOutlined,
  CloudOutlined,
  CodeOutlined,
  ControlOutlined,
  DashboardOutlined,
  DatabaseOutlined,
  DeploymentUnitOutlined,
  DesktopOutlined,
  EditOutlined,
  ExperimentOutlined,
  FileDoneOutlined,
  FileSearchOutlined,
  FileTextOutlined,
  FolderOutlined,
  HomeOutlined,
  InboxOutlined,
  KeyOutlined,
  LockOutlined,
  MailOutlined,
  MenuOutlined,
  MessageOutlined,
  NotificationOutlined,
  PartitionOutlined,
  PieChartOutlined,
  ProfileOutlined,
  ProjectOutlined,
  ReadOutlined,
  SafetyCertificateOutlined,
  ScheduleOutlined,
  SettingOutlined,
  ShopOutlined,
  SlidersOutlined,
  SolutionOutlined,
  TeamOutlined,
  ToolOutlined,
  UserOutlined,
  UsergroupAddOutlined,
} from '@vicons/antd';

export const constantRouterIcon = {
  ApiOutlined: renderIcon(ApiOutlined),
  ApartmentOutlined: renderIcon(ApartmentOutlined),
  AppstoreOutlined: renderIcon(AppstoreOutlined),
  BgColorsOutlined: renderIcon(BgColorsOutlined),
  BellOutlined: renderIcon(BellOutlined),
  BookOutlined: renderIcon(BookOutlined),
  BugOutlined: renderIcon(BugOutlined),
  BuildOutlined: renderIcon(BuildOutlined),
  CalendarOutlined: renderIcon(CalendarOutlined),
  CloudOutlined: renderIcon(CloudOutlined),
  CodeOutlined: renderIcon(CodeOutlined),
  ControlOutlined: renderIcon(ControlOutlined),
  DashboardOutlined: renderIcon(DashboardOutlined),
  DatabaseOutlined: renderIcon(DatabaseOutlined),
  DeploymentUnitOutlined: renderIcon(DeploymentUnitOutlined),
  DesktopOutlined: renderIcon(DesktopOutlined),
  EditOutlined: renderIcon(EditOutlined),
  ExperimentOutlined: renderIcon(ExperimentOutlined),
  FileDoneOutlined: renderIcon(FileDoneOutlined),
  FileSearchOutlined: renderIcon(FileSearchOutlined),
  FileTextOutlined: renderIcon(FileTextOutlined),
  FolderOutlined: renderIcon(FolderOutlined),
  HomeOutlined: renderIcon(HomeOutlined),
  InboxOutlined: renderIcon(InboxOutlined),
  KeyOutlined: renderIcon(KeyOutlined),
  LockOutlined: renderIcon(LockOutlined),
  MailOutlined: renderIcon(MailOutlined),
  MenuOutlined: renderIcon(MenuOutlined),
  MessageOutlined: renderIcon(MessageOutlined),
  NotificationOutlined: renderIcon(NotificationOutlined),
  PartitionOutlined: renderIcon(PartitionOutlined),
  PieChartOutlined: renderIcon(PieChartOutlined),
  ProfileOutlined: renderIcon(ProfileOutlined),
  ProjectOutlined: renderIcon(ProjectOutlined),
  ReadOutlined: renderIcon(ReadOutlined),
  SafetyCertificateOutlined: renderIcon(SafetyCertificateOutlined),
  ScheduleOutlined: renderIcon(ScheduleOutlined),
  SettingOutlined: renderIcon(SettingOutlined),
  ShopOutlined: renderIcon(ShopOutlined),
  SlidersOutlined: renderIcon(SlidersOutlined),
  SolutionOutlined: renderIcon(SolutionOutlined),
  TeamOutlined: renderIcon(TeamOutlined),
  ToolOutlined: renderIcon(ToolOutlined),
  UserOutlined: renderIcon(UserOutlined),
  UsergroupAddOutlined: renderIcon(UsergroupAddOutlined),
};
