import type { ComponentTokens } from '../types';

export const defaultComponentTokens: ComponentTokens = {
  Button: {
    radius: '{borderRadiusBase}',
    height: '34px',
    paddingX: '{spacingMd}',
    primaryBg: '{primaryColor}',
    primaryBgHover: '{primaryColorHover}',
    primaryBgPressed: '{primaryColorPressed}',
    primaryText: '{white}',
    borderColor: '{borderColorBase}',
  },
  Form: {
    labelTextColor: '{textColorSecondary}',
    feedbackTextColor: '{textColorMuted}',
    itemMarginBottom: '{spacingLg}',
  },
  Input: {
    radius: '{borderRadiusBase}',
    height: '34px',
    borderColor: '{borderColorBase}',
    focusBorderColor: '{primaryColor}',
    bgColor: '{surfaceColor}',
  },
  InputNumber: {
    radius: '{borderRadiusBase}',
    height: '34px',
    borderColor: '{borderColorBase}',
    focusBorderColor: '{primaryColor}',
    bgColor: '{surfaceColor}',
  },
  Select: {
    radius: '{borderRadiusBase}',
    height: '34px',
    borderColor: '{borderColorBase}',
    focusBorderColor: '{primaryColor}',
    bgColor: '{surfaceColor}',
  },
  Switch: {
    railColorActive: '{primaryColor}',
  },
  Checkbox: {
    borderColor: '{borderColorStrong}',
    borderColorChecked: '{primaryColor}',
  },
  Radio: {
    borderColor: '{borderColorStrong}',
    dotColorActive: '{primaryColor}',
  },
  DataTable: {
    bodyBg: '{surfaceColor}',
    headerBg: '{surfaceMutedColor}',
    headerHoverBg: '{surfaceMutedColor}',
    rowHoverBg: '{primaryColorSoft}',
    rowStripedBg: '{surfaceMutedColor}',
    rowSortingBg: '{surfaceMutedColor}',
    rowSelectedBg: '{primaryColorSoft}',
    rowSelectedHoverBg: '{primaryColorSoft}',
    borderColor: '{borderColorBase}',
    thTextColor: '{textColorSecondary}',
    tdTextColor: '{textColorBase}',
    thHeight: '44px',
    tdHeight: '44px',
    cellPaddingX: '12px',
    cellPaddingY: '8px',
    radius: '{borderRadiusBase}',
    selectionColor: '{primaryColor}',
    selectionBorderColor: '{primaryColor}',
  },
  StatusTag: {
    radius: '{radiusSm}',
    height: '24px',
    paddingX: '8px',
    fontWeight: '500',
    successText: '#047857',
    successBg: '#ecfdf5',
    successBorder: '#a7f3d0',
    warningText: '#b45309',
    warningBg: '#fffbeb',
    warningBorder: '#fde68a',
    errorText: '#be123c',
    errorBg: '#fff1f2',
    errorBorder: '#fecdd3',
    infoText: '{primaryColor}',
    infoBg: '{primaryColorSoft}',
    infoBorder: '{blue100}',
    neutralText: '{textColorSecondary}',
    neutralBg: '{surfaceMutedColor}',
    neutralBorder: '{borderColorBase}',
  },
  TableAction: {
    gap: '8px',
    buttonHeight: '30px',
    buttonPaddingX: '12px',
    buttonRadius: '{borderRadiusBase}',
  },
  Pagination: {
    itemRadius: '{borderRadiusBase}',
    itemBorderColor: '{borderColorBase}',
    itemColorActive: '{primaryColor}',
  },
  Dropdown: {
    radius: '{borderRadiusBase}',
    borderColor: '{borderColorBase}',
    bgColor: '{surfaceColor}',
    shadow: '{shadowBase}',
  },
  Tag: {
    radius: '{radiusSm}',
    primaryText: '{textColorSecondary}',
    primaryBg: '{surfaceMutedColor}',
    borderColor: '{borderColorBase}',
  },
  Card: {
    radius: '{borderRadiusBase}',
    borderColor: '{borderColorBase}',
    bgColor: '{surfaceColor}',
    shadow: '{shadowBase}',
  },
  Modal: {
    radius: '{radiusLg}',
    borderColor: '{borderColorBase}',
    bgColor: '{surfaceColor}',
    shadow: '{shadowMd}',
  },
  Drawer: {
    radius: '0px',
    borderColor: '{borderColorBase}',
    bgColor: '{surfaceColor}',
    shadow: '{shadowMd}',
  },
  Menu: {
    itemHeight: '40px',
    itemTextColor: '{textColorSecondary}',
    itemTextColorActive: '{primaryColor}',
    itemBgActive: '{primaryColorSoft}',
    itemBgHover: '{surfaceMutedColor}',
    itemTextColorInverted: '{textColorSecondary}',
    itemTextColorActiveInverted: '{primaryColor}',
    itemBgActiveInverted: '{primaryColorSoft}',
    itemBgHoverInverted: '#0000',
  },
  Tooltip: {
    bgColor: '{gray900}',
    textColor: '{white}',
  },
  LoadingBar: {
    color: '{primaryColor}',
  },
};
