import type { ComponentTokens } from '../types';

export const defaultComponentTokens: ComponentTokens = {
  Button: {
    radius: '{borderRadiusBase}',
    height: '34px',
    paddingX: '{spacingMd}',
    primaryBg: '{primaryColor}',
    primaryBgHover: '{primaryColorHover}',
    primaryBgPressed: '{primaryColorPressed}',
    primaryText: '{white}',
    borderColor: '{borderColorBase}',
  },
  Form: {
    labelTextColor: '{textColorSecondary}',
    feedbackTextColor: '{textColorMuted}',
    itemMarginBottom: '{spacingLg}',
  },
  Input: {
    radius: '{borderRadiusBase}',
    height: '34px',
    borderColor: '{borderColorBase}',
    focusBorderColor: '{primaryColor}',
    bgColor: '{surfaceColor}',
  },
  InputNumber: {
    radius: '{borderRadiusBase}',
    height: '34px',
    borderColor: '{borderColorBase}',
    focusBorderColor: '{primaryColor}',
    bgColor: '{surfaceColor}',
  },
  Select: {
    radius: '{borderRadiusBase}',
    height: '34px',
    borderColor: '{borderColorBase}',
    focusBorderColor: '{primaryColor}',
    bgColor: '{surfaceColor}',
  },
  Switch: {
    railColorActive: '{primaryColor}',
  },
  Checkbox: {
    borderColor: '{borderColorStrong}',
    borderColorChecked: '{primaryColor}',
  },
  Radio: {
    borderColor: '{borderColorStrong}',
    dotColorActive: '{primaryColor}',
  },
  DataTable: {
    bodyBg: '{surfaceColor}',
    headerBg: '{surfaceMutedColor}',
    headerHoverBg: '{surfaceMutedColor}',
    rowHoverBg: '{primaryColorSoft}',
    rowStripedBg: '{surfaceMutedColor}',
    rowSortingBg: '{surfaceMutedColor}',
    rowSelectedBg: '{primaryColorSoft}',
    rowSelectedHoverBg: '{primaryColorSoft}',
    borderColor: '{borderColorBase}',
    thTextColor: '{textColorSecondary}',
    tdTextColor: '{textColorBase}',
    thHeight: '44px',
    tdHeight: '44px',
    cellPaddingX: '12px',
    cellPaddingY: '8px',
    radius: '{borderRadiusBase}',
    selectionColor: '{primaryColor}',
    selectionBorderColor: '{primaryColor}',
    selectionColumnWidth: '48px',
    fixedColumnShadow: 'inset 10px 0 8px -8px rgb(15 23 42 / 12%)',
    emptyTextColor: '{textColorMuted}',
    loadingColor: '{primaryColor}',
    expandedRowBg: '{surfaceMutedColor}',
  },
  TableToolbar: {
    minHeight: '44px',
    bgColor: '{surfaceColor}',
    borderColor: '{borderColorBase}',
    radius: '{borderRadiusBase}',
    paddingX: '12px',
    paddingY: '10px',
    gap: '12px',
    titleTextColor: '{textColorBase}',
    iconColor: '{textColorSecondary}',
    iconHoverBg: '{surfaceMutedColor}',
    iconHoverColor: '{primaryColor}',
  },
  TableSearch: {
    bgColor: '{surfaceColor}',
    borderColor: '{borderColorBase}',
    radius: '{borderRadiusBase}',
    paddingX: '12px',
    paddingY: '12px',
    fieldGap: '12px',
    rowGap: '10px',
    labelWidth: '88px',
    inputWidth: '220px',
    actionGap: '8px',
  },
  TableBatchAction: {
    minHeight: '40px',
    bgColor: '{primaryColorSoft}',
    borderColor: '{borderColorBase}',
    radius: '{borderRadiusBase}',
    paddingX: '12px',
    gap: '8px',
    textColor: '{textColorBase}',
  },
  StatusTag: {
    radius: '{radiusSm}',
    height: '24px',
    paddingX: '8px',
    fontWeight: '500',
    successText: '#047857',
    successBg: '#ecfdf5',
    successBorder: '#a7f3d0',
    warningText: '#b45309',
    warningBg: '#fffbeb',
    warningBorder: '#fde68a',
    errorText: '#be123c',
    errorBg: '#fff1f2',
    errorBorder: '#fecdd3',
    infoText: '{primaryColor}',
    infoBg: '{primaryColorSoft}',
    infoBorder: '{blue100}',
    neutralText: '{textColorSecondary}',
    neutralBg: '{surfaceMutedColor}',
    neutralBorder: '{borderColorBase}',
  },
  TableAction: {
    gap: '8px',
    buttonHeight: '30px',
    buttonPaddingX: '12px',
    buttonRadius: '{borderRadiusBase}',
    defaultTextColor: '{primaryColor}',
    defaultBgColor: '{surfaceColor}',
    defaultBorderColor: '{borderColorBase}',
    primaryTextColor: '{white}',
    primaryBgColor: '{primaryColor}',
    primaryBorderColor: '{primaryColor}',
    dangerTextColor: '{semantic.errorColor}',
    dangerBgColor: '{surfaceColor}',
    dangerBorderColor: '{semantic.errorColor}',
    disabledTextColor: '{textColorMuted}',
    disabledBgColor: '{surfaceMutedColor}',
    disabledBorderColor: '{borderColorBase}',
    moreIconColor: '{textColorSecondary}',
    confirmWidth: '220px',
    confirmRadius: '{borderRadiusBase}',
    confirmBgColor: '{surfaceColor}',
    confirmBorderColor: '{borderColorBase}',
    confirmShadow: '{shadowBase}',
  },
  Pagination: {
    itemRadius: '{borderRadiusBase}',
    itemBorderColor: '{borderColorBase}',
    itemColorActive: '{primaryColor}',
  },
  Dropdown: {
    radius: '{borderRadiusBase}',
    borderColor: '{borderColorBase}',
    bgColor: '{surfaceColor}',
    shadow: '{shadowBase}',
  },
  Tag: {
    radius: '{radiusSm}',
    primaryText: '{textColorSecondary}',
    primaryBg: '{surfaceMutedColor}',
    borderColor: '{borderColorBase}',
  },
  Card: {
    radius: '{borderRadiusBase}',
    borderColor: '{borderColorBase}',
    bgColor: '{surfaceColor}',
    shadow: '{shadowBase}',
  },
  Modal: {
    radius: '{radiusLg}',
    borderColor: '{borderColorBase}',
    bgColor: '{surfaceColor}',
    shadow: '{shadowMd}',
  },
  Drawer: {
    radius: '0px',
    borderColor: '{borderColorBase}',
    bgColor: '{surfaceColor}',
    shadow: '{shadowMd}',
  },
  Menu: {
    itemHeight: '40px',
    itemTextColor: '{textColorSecondary}',
    itemTextColorActive: '{primaryColor}',
    itemBgActive: '{primaryColorSoft}',
    itemBgHover: '{surfaceMutedColor}',
    itemTextColorInverted: '{textColorSecondary}',
    itemTextColorActiveInverted: '{primaryColor}',
    itemBgActiveInverted: '{primaryColorSoft}',
    itemBgHoverInverted: '#0000',
  },
  Tree: {
    nodeHeight: '34px',
    indent: '22px',
    nodeRadius: '{borderRadiusBase}',
    textColor: '{textColorBase}',
    textColorSelected: '{primaryColor}',
    iconColor: '{textColorSecondary}',
    iconSize: '18px',
    hoverBg: '{surfaceMutedColor}',
    selectedBg: '{primaryColorSoft}',
    disabledTextColor: '{textColorMuted}',
    lineColor: '{borderColorBase}',
  },
  Upload: {
    itemSize: '100px',
    itemPadding: '8px',
    itemRadius: '{borderRadiusBase}',
    itemBgColor: '{surfaceColor}',
    itemBorderColor: '{borderColorBase}',
    itemBorderHoverColor: '{primaryColor}',
    triggerBgColor: '{surfaceMutedColor}',
    triggerTextColor: '{textColorSecondary}',
    hintTextColor: '{textColorMuted}',
    iconColor: '{textColorSecondary}',
    overlayBgColor: '#0f172a94',
    actionIconColor: '#ffffffdb',
    actionIconHoverColor: '{white}',
    progressColor: '{primaryColor}',
    errorColor: '{semantic.errorColor}',
  },
  Popup: {
    bgColor: '{surfaceColor}',
    borderColor: '{borderColorBase}',
    shadow: '{shadowBase}',
    radius: '{borderRadiusBase}',
    optionHeight: '34px',
    optionTextColor: '{textColorBase}',
    optionHoverBg: '{surfaceMutedColor}',
    optionActiveBg: '{primaryColorSoft}',
    optionActiveTextColor: '{primaryColor}',
    optionDisabledTextColor: '{textColorMuted}',
    dividerColor: '{borderColorBase}',
  },
  Picker: {
    itemSize: '32px',
    itemRadius: '{radiusSm}',
    itemHoverBg: '{surfaceMutedColor}',
    itemActiveBg: '{primaryColor}',
    itemActiveTextColor: '{white}',
    itemDisabledTextColor: '{textColorMuted}',
    panelHeaderTextColor: '{textColorBase}',
    iconColor: '{textColorSecondary}',
  },
  Tooltip: {
    bgColor: '{gray900}',
    textColor: '{white}',
  },
  LoadingBar: {
    color: '{primaryColor}',
  },
};
