import type { ComponentTokens } from '../types';

export const defaultDarkComponentTokens: Partial<
  Record<keyof ComponentTokens, Record<string, string>>
> = {
  StatusTag: {
    successText: '#86efac',
    successBg: '#052e1a',
    successBorder: '#166534',
    warningText: '#fcd34d',
    warningBg: '#3b2a05',
    warningBorder: '#92400e',
    errorText: '#fb7185',
    errorBg: '#3f111f',
    errorBorder: '#9f1239',
    infoText: '#93c5fd',
    infoBg: '{primaryColorSoft}',
    infoBorder: '#1d4ed8',
    neutralText: '{textColorSecondary}',
    neutralBg: '{surfaceMutedColor}',
    neutralBorder: '{borderColorBase}',
  },
  TableAction: {
    defaultTextColor: '#93c5fd',
    defaultBgColor: '#111827',
    defaultBorderColor: '#334155',
    dangerTextColor: '#fb7185',
    dangerBgColor: '#111827',
    dangerBorderColor: '#e11d48',
    disabledTextColor: '#94a3b8',
    disabledBgColor: '#0f172a',
    disabledBorderColor: '#334155',
  },
  Menu: {
    bgColor: '#0f172a',
    bgColorInverted: '#0f172a',
    itemTextColor: '#cbd5e1',
    itemTextColorActive: '#93c5fd',
    itemBgActive: '#172554',
    itemBgHover: '#1e293b',
    itemTextColorInverted: '#cbd5e1',
    itemTextColorActiveInverted: '#ffffff',
    itemBgActiveInverted: '#1e3a8a',
    itemBgHoverInverted: '#1e293b',
  },
  Popup: {
    bgColor: '#111827',
    borderColor: '#334155',
    optionTextColor: '#f8fafc',
    optionHoverBg: '#1f2937',
    optionActiveBg: '#172554',
    optionActiveTextColor: '#ffffff',
    optionDisabledTextColor: '#64748b',
    dividerColor: '#334155',
  },
  Alert: {
    infoBg: '{primaryColorSoft}',
    infoText: '{textColorBase}',
    infoBorder: '#1d4ed8',
    successBg: '#052e1a',
    successText: '#dcfce7',
    successBorder: '#166534',
    warningBg: '#3b2a05',
    warningText: '#fef3c7',
    warningBorder: '#92400e',
    errorBg: '#3f111f',
    errorText: '#ffe4e6',
    errorBorder: '#9f1239',
  },
};
