import {
  SearchOutlined,
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  FullscreenOutlined,
  FullscreenExitOutlined,
  PoweroffOutlined,
  LockOutlined,
  ReloadOutlined,
  LogoutOutlined,
  BellOutlined,
  MessageOutlined,
  UserOutlined,
  CheckOutlined,
  ApartmentOutlined,
} from '@vicons/antd';
import { Moon, SunnySharp } from '@vicons/ionicons5';

export default {
  LockOutlined,
  SearchOutlined,
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  FullscreenOutlined,
  FullscreenExitOutlined,
  PoweroffOutlined,
  ReloadOutlined,
  LogoutOutlined,
  BellOutlined,
  MessageOutlined,
  UserOutlined,
  CheckOutlined,
  ApartmentOutlined,
  Moon,
  SunnySharp,
};
