import type { AppearancePreset } from '../types';
import { defaultPreset } from './default';

export const primevueLikePreset: AppearancePreset = {
  id: 'primevue-like',
  name: 'PrimeVue 风格',
  description: '白色内容面、清晰边框、扁平控件和适中的企业后台密度。',
  skinClass: 'skin-primevue-like',
  tokens: {
    primitive: {
      ...defaultPreset.tokens.primitive,
      blue50: '#eff6ff',
      blue100: '#dbeafe',
      blue500: '#2563eb',
      blue600: '#1d4ed8',
      gray50: '#f8fafc',
      gray100: '#f1f5f9',
      gray200: '#e2e8f0',
      gray300: '#cbd5e1',
      gray500: '#64748b',
      gray700: '#334155',
      gray900: '#0f172a',
      radiusMd: '6px',
      radiusLg: '8px',
      shadowSm: '0 1px 2px rgb(15 23 42 / 4%)',
      shadowMd: '0 10px 24px rgb(15 23 42 / 10%)',
    },
    semantic: {
      ...defaultPreset.tokens.semantic,
      pageBgColor: '{gray50}',
      primaryColorSoft: '{blue50}',
      borderColorBase: '{gray200}',
      borderColorStrong: '{gray300}',
      borderRadiusBase: '{radiusMd}',
    },
    component: {
      ...defaultPreset.tokens.component,
      Button: {
        ...defaultPreset.tokens.component.Button,
        height: '36px',
        paddingX: '14px',
      },
      Input: {
        ...defaultPreset.tokens.component.Input,
        height: '36px',
      },
      InputNumber: {
        ...defaultPreset.tokens.component.InputNumber,
        height: '36px',
      },
      Select: {
        ...defaultPreset.tokens.component.Select,
        height: '36px',
      },
      DataTable: {
        ...defaultPreset.tokens.component.DataTable,
        headerBg: '{surfaceMutedColor}',
        headerHoverBg: '{surfaceMutedColor}',
        rowHoverBg: '{primaryColorSoft}',
        rowStripedBg: '{pageBgColor}',
        rowSortingBg: '{primaryColorSoft}',
        rowSelectedBg: '{primaryColorSoft}',
        rowSelectedHoverBg: '{primaryColorSoft}',
        thHeight: '46px',
        tdHeight: '46px',
        radius: '{borderRadiusBase}',
        fixedColumnShadow: 'inset 10px 0 8px -8px rgb(15 23 42 / 10%)',
      },
      TableToolbar: {
        ...defaultPreset.tokens.component.TableToolbar,
        minHeight: '46px',
        bgColor: '{surfaceColor}',
        paddingX: '12px',
        paddingY: '10px',
      },
      TableSearch: {
        ...defaultPreset.tokens.component.TableSearch,
        bgColor: '{surfaceColor}',
        inputWidth: '240px',
      },
      TableBatchAction: {
        ...defaultPreset.tokens.component.TableBatchAction,
        bgColor: '{primaryColorSoft}',
      },
      TableAction: {
        ...defaultPreset.tokens.component.TableAction,
        buttonHeight: '32px',
        buttonPaddingX: '12px',
        confirmShadow: '0 12px 28px rgb(15 23 42 / 12%)',
      },
      Menu: {
        ...defaultPreset.tokens.component.Menu,
        itemHeight: '42px',
        itemBgActive: '{primaryColorSoft}',
        itemBgHover: '{surfaceMutedColor}',
        itemTextColorInverted: '#94a3b8',
        itemTextColorActiveInverted: '#ffffff',
        itemBgActiveInverted: '{primaryColor}',
        itemBgHoverInverted: '#0000',
      },
      Tree: {
        ...defaultPreset.tokens.component.Tree,
        nodeHeight: '34px',
        hoverBg: '{surfaceMutedColor}',
        selectedBg: '{primaryColorSoft}',
      },
      Upload: {
        ...defaultPreset.tokens.component.Upload,
        itemRadius: '{borderRadiusBase}',
        triggerBgColor: '{surfaceMutedColor}',
        itemBorderHoverColor: '{primaryColor}',
      },
      Card: {
        ...defaultPreset.tokens.component.Card,
        shadow: '{shadowNone}',
      },
    },
    layout: {
      ...defaultPreset.tokens.layout,
      contentPadding: 14,
      cardStyle: 'bordered',
    },
  },
  darkSemantic: {
    ...defaultPreset.darkSemantic,
    primaryColor: '{blue500}',
    primaryColorHover: '{blue500}',
    primaryColorPressed: '{blue600}',
    primaryColorSoft: '#172554',
    pageBgColor: '#0f172a',
    surfaceColor: '#111827',
    surfaceMutedColor: '#1e293b',
    textColorBase: '#f8fafc',
    textColorSecondary: '#cbd5e1',
    textColorMuted: '#94a3b8',
    borderColorBase: '#334155',
    borderColorStrong: '#475569',
    shadowBase: '0 10px 24px rgb(0 0 0 / 24%)',
  },
};
