from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Protocol


@dataclass(frozen=True)
class RecipientProfile:
    user_id: int
    username: str
    tenant_id: int


class RecipientDirectoryPort(Protocol):
    def resolve_users(self, tenant_id: int, target: dict[str, Any]) -> list[RecipientProfile]:
        ...


class MessagingRepository(Protocol):
    def __getattr__(self, name: str) -> Any: ...

    def create_message(self, *args: Any, **kwargs: Any) -> Any: ...
    def list_messages(self, *args: Any, **kwargs: Any) -> Any: ...
    def list_inbox(self, *args: Any, **kwargs: Any) -> Any: ...
    def unread_count(self, *args: Any, **kwargs: Any) -> int: ...
    def mark_read(self, *args: Any, **kwargs: Any) -> Any: ...
    def mark_all_read(self, *args: Any, **kwargs: Any) -> int: ...
    def list_templates(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_template_by_key(self, *args: Any, **kwargs: Any) -> Any: ...
    def save_template(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_template_status(self, *args: Any, **kwargs: Any) -> Any: ...
    def list_channel_accounts(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_channel_account(self, *args: Any, **kwargs: Any) -> Any: ...
    def save_channel_account(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_channel_account_enabled(self, *args: Any, **kwargs: Any) -> Any: ...
    def list_chat_bots(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_chat_bot(self, *args: Any, **kwargs: Any) -> Any: ...
    def save_chat_bot(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_chat_bot_enabled(self, *args: Any, **kwargs: Any) -> Any: ...
    def update_chat_bot_test_result(self, *args: Any, **kwargs: Any) -> Any: ...
    def list_preferences(self, *args: Any, **kwargs: Any) -> Any: ...
    def save_preferences(self, *args: Any, **kwargs: Any) -> Any: ...


@dataclass(frozen=True)
class ChatBotDeliveryResult:
    ok: bool
    status_code: int
    message: str
    request: dict[str, Any]
    response: dict[str, Any]


class ChatBotSenderPort(Protocol):
    def send(self, *, chat_bot: Any, title: str, content: str) -> ChatBotDeliveryResult:
        ...


class UnavailableChatBotSender:
    def send(self, *, chat_bot: Any, title: str, content: str) -> ChatBotDeliveryResult:
        return ChatBotDeliveryResult(
            ok=False,
            status_code=0,
            message="群聊机器人发送适配器尚未接入",
            request={"chat_bot_id": getattr(chat_bot, "id", None), "title": title, "content": content},
            response={},
        )

