from __future__ import annotations

from typing import Any, Protocol


class LLMRuntimeRepository(Protocol):
    def __getattr__(self, name: str) -> Any: ...
    def require_llm_schema(self, *args: Any, **kwargs: Any) -> Any: ...

    def list_providers(self, *args: Any, **kwargs: Any) -> Any: ...
    def upsert_provider(self, *args: Any, **kwargs: Any) -> Any: ...
    def list_models(self, *args: Any, **kwargs: Any) -> Any: ...
    def upsert_model(self, *args: Any, **kwargs: Any) -> Any: ...
    def list_tasks(self, *args: Any, **kwargs: Any) -> Any: ...
    def register_task(self, *args: Any, **kwargs: Any) -> Any: ...
    def list_policies(self, *args: Any, **kwargs: Any) -> Any: ...
    def upsert_routing_policy(self, *args: Any, **kwargs: Any) -> Any: ...
    def list_call_logs(self, *args: Any, **kwargs: Any) -> Any: ...
    def resolve_route(self, *args: Any, **kwargs: Any) -> Any: ...
    def entry_for_model(self, *args: Any, **kwargs: Any) -> Any: ...
    def record_call_log(self, *args: Any, **kwargs: Any) -> Any: ...
