from __future__ import annotations

from typing import Any, Protocol


class AIAssetsRepository(Protocol):
    def __getattr__(self, name: str) -> Any: ...

    def list_prompt_assets(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_prompt_asset(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_prompt_asset_by_key(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_published_prompt_version(self, *args: Any, **kwargs: Any) -> Any: ...
    def save_prompt_asset(self, *args: Any, **kwargs: Any) -> Any: ...
    def copy_prompt_asset(self, *args: Any, **kwargs: Any) -> Any: ...
    def prompt_name_exists(self, *args: Any, **kwargs: Any) -> bool: ...
    def prompt_key_exists(self, *args: Any, **kwargs: Any) -> bool: ...
    def archive_prompt_asset(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete_archived_prompt_asset(self, *args: Any, **kwargs: Any) -> Any: ...
    def list_prompt_versions(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_prompt_version(self, *args: Any, **kwargs: Any) -> Any: ...
    def save_prompt_version(self, *args: Any, **kwargs: Any) -> Any: ...
    def count_prompt_versions_by_status(self, *args: Any, **kwargs: Any) -> int: ...
    def set_prompt_version_status(self, *args: Any, **kwargs: Any) -> Any: ...
    def list_skill_assets(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_skill_asset(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_skill_asset_by_key(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_published_skill_version(self, *args: Any, **kwargs: Any) -> Any: ...
    def save_skill_asset(self, *args: Any, **kwargs: Any) -> Any: ...
    def skill_name_exists(self, *args: Any, **kwargs: Any) -> bool: ...
    def skill_key_exists(self, *args: Any, **kwargs: Any) -> bool: ...
    def archive_skill_asset(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete_archived_skill_asset(self, *args: Any, **kwargs: Any) -> Any: ...
    def list_skill_versions(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_skill_version(self, *args: Any, **kwargs: Any) -> Any: ...
    def save_skill_version(self, *args: Any, **kwargs: Any) -> Any: ...
    def count_skill_versions_by_status(self, *args: Any, **kwargs: Any) -> int: ...
    def set_skill_version_status(self, *args: Any, **kwargs: Any) -> Any: ...
    def now_iso(self) -> str: ...
