import type { AppearanceCssVars, AppearanceTokens } from './types';

export function createAppearanceCssVars(tokens: AppearanceTokens): AppearanceCssVars {
  const { primitive, semantic, component, layout } = tokens;

  return {
    '--app-page-bg': semantic.pageBgColor,
    '--app-surface-bg': semantic.surfaceColor,
    '--app-surface-muted-bg': semantic.surfaceMutedColor,
    '--app-content-margin': `0 ${layout.contentPadding}px ${layout.contentPadding}px`,
    '--app-content-padding': `${layout.contentPadding}px`,
    '--app-header-height': `${layout.headerHeight}px`,
    '--app-tabs-height': `${layout.tabsHeight}px`,
    '--app-menu-width': `${layout.menuWidth}px`,
    '--app-collapsed-menu-width': `${layout.collapsedMenuWidth}px`,
    '--app-border-color': semantic.borderColorBase,
    '--app-card-bg': component.Card.bgColor,
    '--app-card-border-color': component.Card.borderColor,
    '--app-card-radius': component.Card.radius,
    '--app-card-shadow': component.Card.shadow,
    '--app-table-radius': component.DataTable.radius,
    '--app-table-selection-color': component.DataTable.selectionColor,
    '--app-table-selection-border-color': component.DataTable.selectionBorderColor,
    '--app-status-tag-radius': component.StatusTag.radius,
    '--app-status-tag-height': component.StatusTag.height,
    '--app-status-tag-padding-x': component.StatusTag.paddingX,
    '--app-status-tag-font-weight': component.StatusTag.fontWeight,
    '--app-status-success-text': component.StatusTag.successText,
    '--app-status-success-bg': component.StatusTag.successBg,
    '--app-status-success-border': component.StatusTag.successBorder,
    '--app-status-warning-text': component.StatusTag.warningText,
    '--app-status-warning-bg': component.StatusTag.warningBg,
    '--app-status-warning-border': component.StatusTag.warningBorder,
    '--app-status-error-text': component.StatusTag.errorText,
    '--app-status-error-bg': component.StatusTag.errorBg,
    '--app-status-error-border': component.StatusTag.errorBorder,
    '--app-status-info-text': component.StatusTag.infoText,
    '--app-status-info-bg': component.StatusTag.infoBg,
    '--app-status-info-border': component.StatusTag.infoBorder,
    '--app-status-neutral-text': component.StatusTag.neutralText,
    '--app-status-neutral-bg': component.StatusTag.neutralBg,
    '--app-status-neutral-border': component.StatusTag.neutralBorder,
    '--app-table-action-gap': component.TableAction.gap,
    '--app-table-action-button-height': component.TableAction.buttonHeight,
    '--app-table-action-button-padding-x': component.TableAction.buttonPaddingX,
    '--app-table-action-button-radius': component.TableAction.buttonRadius,
    '--app-shadow-sm': semantic.shadowBase,
    '--app-icon-color': semantic.textColorSecondary,
    '--app-icon-hover-bg': semantic.surfaceMutedColor,
    '--app-font-family-base': semantic.fontFamilyBase,
    '--app-font-size-xs': primitive.fontSizeXs,
    '--app-font-size-sm': primitive.fontSizeSm,
    '--app-font-size-md': primitive.fontSizeMd,
    '--app-font-size-lg': primitive.fontSizeLg,
    '--app-font-size-base': semantic.fontSizeBase,
    '--app-primary-color': semantic.primaryColor,
    '--app-primary-hover-color': semantic.primaryColorHover,
    '--app-primary-pressed-color': semantic.primaryColorPressed,
    '--app-primary-soft-bg': semantic.primaryColorSoft,
    '--app-text-color': semantic.textColorBase,
  };
}
