import type { GlobalThemeOverrides } from 'naive-ui';
import type { AppearanceTokens } from './types';

export function createNaiveThemeOverrides(tokens: AppearanceTokens): GlobalThemeOverrides {
  const { semantic, component } = tokens;
  const primary = semantic.primaryColor;
  const radius = semantic.borderRadiusBase;

  return {
    common: {
      primaryColor: primary,
      primaryColorHover: semantic.primaryColorHover,
      primaryColorPressed: semantic.primaryColorPressed,
      primaryColorSuppl: semantic.primaryColorHover,
      successColor: semantic.successColor,
      warningColor: semantic.warningColor,
      errorColor: semantic.errorColor,
      infoColor: semantic.infoColor,
      textColorBase: semantic.textColorBase,
      textColor2: semantic.textColorSecondary,
      borderColor: semantic.borderColorBase,
      borderRadius: radius,
      fontFamily: semantic.fontFamilyBase,
      fontSize: semantic.fontSizeBase,
      bodyColor: semantic.pageBgColor,
      cardColor: semantic.surfaceColor,
    },
    Button: {
      borderRadiusSmall: component.Button.radius,
      borderRadiusMedium: component.Button.radius,
      borderRadiusLarge: component.Button.radius,
      heightSmall: component.Button.height,
      heightMedium: component.Button.height,
      heightLarge: component.Button.height,
      paddingMedium: `0 ${component.Button.paddingX}`,
      colorPrimary: component.Button.primaryBg,
      colorHoverPrimary: component.Button.primaryBgHover,
      colorPressedPrimary: component.Button.primaryBgPressed,
      colorFocusPrimary: component.Button.primaryBgHover,
      colorDisabledPrimary: component.Button.primaryBg,
      textColorPrimary: component.Button.primaryText,
      textColorHoverPrimary: component.Button.primaryText,
      textColorPressedPrimary: component.Button.primaryText,
      textColorFocusPrimary: component.Button.primaryText,
      textColorDisabledPrimary: component.Button.primaryText,
      border: `1px solid ${component.Button.borderColor}`,
      borderPrimary: `1px solid ${component.Button.primaryBg}`,
      borderHoverPrimary: `1px solid ${component.Button.primaryBgHover}`,
      borderPressedPrimary: `1px solid ${component.Button.primaryBgPressed}`,
      borderFocusPrimary: `1px solid ${component.Button.primaryBgHover}`,
      borderDisabledPrimary: `1px solid ${component.Button.primaryBg}`,
    },
    Form: {
      labelTextColor: component.Form.labelTextColor,
      feedbackTextColor: component.Form.feedbackTextColor,
      feedbackHeightMedium: component.Form.itemMarginBottom,
    },
    Input: {
      borderRadius: component.Input.radius,
      heightMedium: component.Input.height,
      color: component.Input.bgColor,
      border: `1px solid ${component.Input.borderColor}`,
      borderHover: `1px solid ${component.Input.focusBorderColor}`,
      borderFocus: `1px solid ${component.Input.focusBorderColor}`,
    },
    InputNumber: {
      borderRadius: component.InputNumber.radius,
      heightMedium: component.InputNumber.height,
      color: component.InputNumber.bgColor,
      border: `1px solid ${component.InputNumber.borderColor}`,
      borderHover: `1px solid ${component.InputNumber.focusBorderColor}`,
      borderFocus: `1px solid ${component.InputNumber.focusBorderColor}`,
    },
    Select: {
      peers: {
        InternalSelection: {
          borderRadius: component.Select.radius,
          heightMedium: component.Select.height,
          color: component.Select.bgColor,
          border: `1px solid ${component.Select.borderColor}`,
          borderHover: `1px solid ${component.Select.focusBorderColor}`,
          borderActive: `1px solid ${component.Select.focusBorderColor}`,
        },
        InternalSelectMenu: {
          borderRadius: component.Popup.radius,
          color: component.Popup.bgColor,
          actionDividerColor: component.Popup.dividerColor,
          optionHeightMedium: component.Popup.optionHeight,
          optionTextColor: component.Popup.optionTextColor,
          optionTextColorPressed: component.Popup.optionActiveTextColor,
          optionTextColorDisabled: component.Popup.optionDisabledTextColor,
          optionTextColorActive: component.Popup.optionActiveTextColor,
          optionCheckColor: component.Popup.optionActiveTextColor,
          optionColorPending: component.Popup.optionHoverBg,
          optionColorActive: component.Popup.optionActiveBg,
          optionColorActivePending: component.Popup.optionActiveBg,
        },
      },
    },
    DatePicker: {
      panelColor: component.Popup.bgColor,
      panelTextColor: component.Popup.optionTextColor,
      panelBoxShadow: component.Popup.shadow,
      panelBorderRadius: component.Popup.radius,
      panelHeaderDividerColor: component.Popup.dividerColor,
      panelActionDividerColor: component.Popup.dividerColor,
      calendarDividerColor: component.Popup.dividerColor,
      calendarDaysDividerColor: component.Popup.dividerColor,
      calendarTitleTextColor: component.Picker.panelHeaderTextColor,
      calendarTitleColorHover: component.Popup.optionHoverBg,
      calendarDaysTextColor: component.Popup.optionTextColor,
      arrowColor: component.Picker.iconColor,
      iconColor: component.Picker.iconColor,
      iconColorDisabled: component.Popup.optionDisabledTextColor,
      itemTextColor: component.Popup.optionTextColor,
      itemTextColorDisabled: component.Picker.itemDisabledTextColor,
      itemTextColorActive: component.Picker.itemActiveTextColor,
      itemTextColorCurrent: component.Popup.optionActiveTextColor,
      itemColorHover: component.Picker.itemHoverBg,
      itemColorActive: component.Picker.itemActiveBg,
      itemColorIncluded: component.Popup.optionActiveBg,
      itemColorDisabled: component.Popup.bgColor,
      itemBorderRadius: component.Picker.itemRadius,
      scrollItemBorderRadius: component.Picker.itemRadius,
      itemSize: component.Picker.itemSize,
      itemCellHeight: component.Picker.itemSize,
    },
    TimePicker: {
      panelColor: component.Popup.bgColor,
      panelBoxShadow: component.Popup.shadow,
      panelDividerColor: component.Popup.dividerColor,
      borderRadius: component.Popup.radius,
      itemHeight: component.Popup.optionHeight,
      itemTextColor: component.Popup.optionTextColor,
      itemTextColorActive: component.Popup.optionActiveTextColor,
      itemColorHover: component.Popup.optionHoverBg,
      itemBorderRadius: component.Picker.itemRadius,
      iconColor: component.Picker.iconColor,
      iconColorDisabled: component.Popup.optionDisabledTextColor,
    },
    AutoComplete: {
      menuBoxShadow: component.Popup.shadow,
      peers: {
        InternalSelectMenu: {
          borderRadius: component.Popup.radius,
          color: component.Popup.bgColor,
          actionDividerColor: component.Popup.dividerColor,
          optionHeightMedium: component.Popup.optionHeight,
          optionTextColor: component.Popup.optionTextColor,
          optionTextColorPressed: component.Popup.optionActiveTextColor,
          optionTextColorDisabled: component.Popup.optionDisabledTextColor,
          optionTextColorActive: component.Popup.optionActiveTextColor,
          optionCheckColor: component.Popup.optionActiveTextColor,
          optionColorPending: component.Popup.optionHoverBg,
          optionColorActive: component.Popup.optionActiveBg,
          optionColorActivePending: component.Popup.optionActiveBg,
        },
      },
    },
    Cascader: {
      menuBorderRadius: component.Popup.radius,
      menuColor: component.Popup.bgColor,
      menuBoxShadow: component.Popup.shadow,
      menuDividerColor: component.Popup.dividerColor,
      optionHeight: component.Popup.optionHeight,
      optionColorHover: component.Popup.optionHoverBg,
      optionTextColor: component.Popup.optionTextColor,
      optionTextColorActive: component.Popup.optionActiveTextColor,
      optionTextColorDisabled: component.Popup.optionDisabledTextColor,
      optionCheckMarkColor: component.Popup.optionActiveTextColor,
      optionArrowColor: component.Picker.iconColor,
      loadingColor: semantic.primaryColor,
    },
    TreeSelect: {
      menuColor: component.Popup.bgColor,
      menuBoxShadow: component.Popup.shadow,
      menuBorderRadius: component.Popup.radius,
      actionDividerColor: component.Popup.dividerColor,
      actionTextColor: component.Popup.optionActiveTextColor,
      headerDividerColor: component.Popup.dividerColor,
      headerTextColor: component.Picker.panelHeaderTextColor,
      peers: {
        Tree: {
          nodeHeight: component.Tree.nodeHeight,
          nodeBorderRadius: component.Tree.nodeRadius,
          nodeTextColor: component.Tree.textColor,
          nodeTextColorSelected: component.Tree.textColorSelected,
          nodeTextColorDisabled: component.Tree.disabledTextColor,
          nodeColorHover: component.Tree.hoverBg,
          nodeColorActive: component.Tree.selectedBg,
          arrowColor: component.Tree.iconColor,
          loadingColor: semantic.primaryColor,
          lineColor: component.Tree.lineColor,
        },
        InternalSelection: {
          borderRadius: component.Select.radius,
          heightMedium: component.Select.height,
          color: component.Select.bgColor,
          border: `1px solid ${component.Select.borderColor}`,
          borderHover: `1px solid ${component.Select.focusBorderColor}`,
          borderActive: `1px solid ${component.Select.focusBorderColor}`,
        },
      },
    },
    Switch: {
      railColorActive: component.Switch.railColorActive,
    },
    Checkbox: {
      border: `1px solid ${component.Checkbox.borderColor}`,
      borderChecked: `1px solid ${component.Checkbox.borderColorChecked}`,
      colorChecked: component.Checkbox.borderColorChecked,
    },
    Radio: {
      dotColorActive: component.Radio.dotColorActive,
      boxShadow: `inset 0 0 0 1px ${component.Radio.borderColor}`,
      boxShadowActive: `inset 0 0 0 1px ${component.Radio.dotColorActive}`,
    },
    DataTable: {
      tdColor: component.DataTable.bodyBg,
      tdColorModal: component.DataTable.bodyBg,
      tdColorPopover: component.DataTable.bodyBg,
      thColor: component.DataTable.headerBg,
      thColorModal: component.DataTable.headerBg,
      thColorPopover: component.DataTable.headerBg,
      thTextColor: component.DataTable.thTextColor,
      tdTextColor: component.DataTable.tdTextColor,
      tdColorHover: component.DataTable.rowHoverBg,
      tdColorHoverModal: component.DataTable.rowHoverBg,
      tdColorHoverPopover: component.DataTable.rowHoverBg,
      tdColorStriped: component.DataTable.rowStripedBg,
      tdColorStripedModal: component.DataTable.rowStripedBg,
      tdColorStripedPopover: component.DataTable.rowStripedBg,
      tdColorSorting: component.DataTable.rowSortingBg,
      tdColorSortingModal: component.DataTable.rowSortingBg,
      tdColorSortingPopover: component.DataTable.rowSortingBg,
      tdColorSelected: component.DataTable.rowSelectedBg,
      tdColorSelectedModal: component.DataTable.rowSelectedBg,
      tdColorSelectedPopover: component.DataTable.rowSelectedBg,
      tdColorSelectedHover: component.DataTable.rowSelectedHoverBg,
      tdColorSelectedHoverModal: component.DataTable.rowSelectedHoverBg,
      tdColorSelectedHoverPopover: component.DataTable.rowSelectedHoverBg,
      borderColor: component.DataTable.borderColor,
      borderColorModal: component.DataTable.borderColor,
      borderColorPopover: component.DataTable.borderColor,
      thColorHover: component.DataTable.headerHoverBg,
      thColorHoverModal: component.DataTable.headerHoverBg,
      thColorHoverPopover: component.DataTable.headerHoverBg,
      thColorSorting: component.DataTable.headerHoverBg,
      thColorSortingModal: component.DataTable.headerHoverBg,
      thColorSortingPopover: component.DataTable.headerHoverBg,
      thHeightMedium: component.DataTable.thHeight,
      tdHeightMedium: component.DataTable.tdHeight,
      thPaddingMedium: `${component.DataTable.cellPaddingY} ${component.DataTable.cellPaddingX}`,
      tdPaddingMedium: `${component.DataTable.cellPaddingY} ${component.DataTable.cellPaddingX}`,
      thButtonColorHover: component.DataTable.headerHoverBg,
      thIconColor: component.DataTable.thTextColor,
      thIconColorActive: component.DataTable.selectionColor,
      loadingColor: component.DataTable.loadingColor,
    },
    Pagination: {
      itemBorderRadius: component.Pagination.itemRadius,
      itemBorderActive: `1px solid ${component.Pagination.itemColorActive}`,
      itemTextColorActive: component.Pagination.itemColorActive,
    },
    Dropdown: {
      borderRadius: component.Dropdown.radius,
      color: component.Dropdown.bgColor,
      boxShadow: component.Dropdown.shadow,
      optionHeightMedium: component.Popup.optionHeight,
      optionTextColor: component.Popup.optionTextColor,
      optionTextColorHover: component.Popup.optionTextColor,
      optionTextColorActive: component.Popup.optionActiveTextColor,
      optionColorHover: component.Popup.optionHoverBg,
      optionColorActive: component.Popup.optionActiveBg,
      dividerColor: component.Popup.dividerColor,
    },
    Tag: {
      borderRadius: component.Tag.radius,
      color: component.Tag.primaryBg,
      textColor: component.Tag.primaryText,
      border: `1px solid ${component.Tag.borderColor}`,
    },
    Card: {
      borderRadius: component.Card.radius,
      color: component.Card.bgColor,
      borderColor: component.Card.borderColor,
      boxShadow: component.Card.shadow,
    },
    Modal: {
      borderRadius: component.Modal.radius,
      color: component.Modal.bgColor,
      boxShadow: component.Modal.shadow,
    },
    Dialog: {
      borderRadius: component.Dialog.radius,
      border: `1px solid ${component.Dialog.borderColor}`,
      color: component.Dialog.bgColor,
      titleTextColor: component.Dialog.titleTextColor,
      textColor: component.Dialog.contentTextColor,
      iconColor: component.Dialog.iconColor,
      iconColorInfo: component.Dialog.iconColor,
      iconColorSuccess: semantic.successColor,
      iconColorWarning: semantic.warningColor,
      iconColorError: semantic.errorColor,
      padding: component.Dialog.padding,
      actionSpace: component.Dialog.actionGap,
      closeIconColor: semantic.textColorSecondary,
      closeIconColorHover: semantic.primaryColor,
      closeColorHover: semantic.surfaceMutedColor,
      peers: {
        Button: {
          borderRadiusSmall: component.Button.radius,
          borderRadiusMedium: component.Button.radius,
          heightSmall: component.Button.height,
          heightMedium: component.Button.height,
          paddingSmall: `0 ${component.Button.paddingX}`,
          paddingMedium: `0 ${component.Button.paddingX}`,
          colorInfo: component.Button.primaryBg,
          colorHoverInfo: component.Button.primaryBgHover,
          colorPressedInfo: component.Button.primaryBgPressed,
          colorFocusInfo: component.Button.primaryBgHover,
          colorDisabledInfo: component.Button.primaryBg,
          textColorInfo: component.Button.primaryText,
          textColorHoverInfo: component.Button.primaryText,
          textColorPressedInfo: component.Button.primaryText,
          textColorFocusInfo: component.Button.primaryText,
          textColorDisabledInfo: component.Button.primaryText,
          borderInfo: `1px solid ${component.Button.primaryBg}`,
          borderHoverInfo: `1px solid ${component.Button.primaryBgHover}`,
          borderPressedInfo: `1px solid ${component.Button.primaryBgPressed}`,
          borderFocusInfo: `1px solid ${component.Button.primaryBgHover}`,
          borderDisabledInfo: `1px solid ${component.Button.primaryBg}`,
          rippleColorInfo: component.Button.primaryBg,
          colorPrimary: component.Button.primaryBg,
          colorHoverPrimary: component.Button.primaryBgHover,
          colorPressedPrimary: component.Button.primaryBgPressed,
          colorFocusPrimary: component.Button.primaryBgHover,
          colorDisabledPrimary: component.Button.primaryBg,
          textColorPrimary: component.Button.primaryText,
          textColorHoverPrimary: component.Button.primaryText,
          textColorPressedPrimary: component.Button.primaryText,
          textColorFocusPrimary: component.Button.primaryText,
          textColorDisabledPrimary: component.Button.primaryText,
          borderPrimary: `1px solid ${component.Button.primaryBg}`,
          borderHoverPrimary: `1px solid ${component.Button.primaryBgHover}`,
          borderPressedPrimary: `1px solid ${component.Button.primaryBgPressed}`,
          borderFocusPrimary: `1px solid ${component.Button.primaryBgHover}`,
          borderDisabledPrimary: `1px solid ${component.Button.primaryBg}`,
          rippleColorPrimary: component.Button.primaryBg,
        },
      },
    },
    Drawer: {
      color: component.Drawer.bgColor,
      boxShadow: component.Drawer.shadow,
    },
    Menu: {
      itemHeight: component.Menu.itemHeight,
      itemTextColor: component.Menu.itemTextColor,
      itemTextColorHover: component.Menu.itemTextColor,
      itemTextColorActive: component.Menu.itemTextColorActive,
      itemTextColorActiveHover: component.Menu.itemTextColorActive,
      itemTextColorChildActive: component.Menu.itemTextColorActive,
      itemTextColorChildActiveHover: component.Menu.itemTextColorActive,
      itemIconColor: component.Menu.itemTextColor,
      itemIconColorHover: component.Menu.itemTextColor,
      itemIconColorActive: component.Menu.itemTextColorActive,
      itemIconColorActiveHover: component.Menu.itemTextColorActive,
      arrowColor: component.Menu.itemTextColor,
      arrowColorHover: component.Menu.itemTextColor,
      arrowColorActive: component.Menu.itemTextColorActive,
      arrowColorActiveHover: component.Menu.itemTextColorActive,
      itemColorActive: component.Menu.itemBgActive,
      itemColorActiveHover: component.Menu.itemBgActive,
      itemColorActiveCollapsed: component.Menu.itemBgActive,
      itemColorHover: component.Menu.itemBgHover,
      itemColorHoverInverted: component.Menu.itemBgHoverInverted,
      itemColorActiveInverted: component.Menu.itemBgActiveInverted,
      itemColorActiveHoverInverted: component.Menu.itemBgActiveInverted,
      itemColorActiveCollapsedInverted: component.Menu.itemBgActiveInverted,
      itemTextColorInverted: component.Menu.itemTextColorInverted,
      itemTextColorHoverInverted: component.Menu.itemTextColorInverted,
      itemTextColorActiveInverted: component.Menu.itemTextColorActiveInverted,
      itemTextColorActiveHoverInverted: component.Menu.itemTextColorActiveInverted,
      itemTextColorChildActiveInverted: component.Menu.itemTextColorActiveInverted,
      itemTextColorChildActiveHoverInverted: component.Menu.itemTextColorActiveInverted,
      itemIconColorInverted: component.Menu.itemTextColorInverted,
      itemIconColorHoverInverted: component.Menu.itemTextColorInverted,
      itemIconColorActiveInverted: component.Menu.itemTextColorActiveInverted,
      itemIconColorActiveHoverInverted: component.Menu.itemTextColorActiveInverted,
      itemIconColorChildActiveInverted: component.Menu.itemTextColorActiveInverted,
      itemIconColorChildActiveHoverInverted: component.Menu.itemTextColorActiveInverted,
      arrowColorInverted: component.Menu.itemTextColorInverted,
      arrowColorHoverInverted: component.Menu.itemTextColorInverted,
      arrowColorActiveInverted: component.Menu.itemTextColorActiveInverted,
      arrowColorActiveHoverInverted: component.Menu.itemTextColorActiveInverted,
      arrowColorChildActiveInverted: component.Menu.itemTextColorActiveInverted,
      arrowColorChildActiveHoverInverted: component.Menu.itemTextColorActiveInverted,
    },
    Tree: {
      nodeHeight: component.Tree.nodeHeight,
      nodeBorderRadius: component.Tree.nodeRadius,
      nodeTextColor: component.Tree.textColor,
      nodeTextColorSelected: component.Tree.textColorSelected,
      nodeTextColorDisabled: component.Tree.disabledTextColor,
      nodeColorHover: component.Tree.hoverBg,
      nodeColorSelected: component.Tree.selectedBg,
      arrowColor: component.Tree.iconColor,
      loadingColor: semantic.primaryColor,
    },
    Upload: {
      itemColorHover: component.Upload.triggerBgColor,
      itemColorHoverError: component.Upload.triggerBgColor,
      itemBorder: `1px solid ${component.Upload.itemBorderColor}`,
      itemBorderHover: `1px solid ${component.Upload.itemBorderHoverColor}`,
      itemBorderHoverError: `1px solid ${component.Upload.errorColor}`,
      itemBorderImageCard: `1px solid ${component.Upload.itemBorderColor}`,
      itemBorderImageCardHover: `1px solid ${component.Upload.itemBorderHoverColor}`,
      draggerColor: component.Upload.triggerBgColor,
      draggerBorder: `1px dashed ${component.Upload.itemBorderColor}`,
      draggerBorderHover: `1px dashed ${component.Upload.itemBorderHoverColor}`,
      draggerTextColor: component.Upload.triggerTextColor,
      draggerTextColorHover: component.Upload.triggerTextColor,
    },
    Tooltip: {
      color: component.Tooltip.bgColor,
      textColor: component.Tooltip.textColor,
    },
    Alert: {
      borderRadius: component.Alert.radius,
      padding: component.Alert.padding,
      colorInfo: component.Alert.infoBg,
      titleTextColorInfo: component.Alert.infoText,
      contentTextColorInfo: component.Alert.infoText,
      iconColorInfo: component.Alert.infoIcon,
      borderInfo: `1px solid ${component.Alert.infoBorder}`,
      colorSuccess: component.Alert.successBg,
      titleTextColorSuccess: component.Alert.successText,
      contentTextColorSuccess: component.Alert.successText,
      iconColorSuccess: component.Alert.successIcon,
      borderSuccess: `1px solid ${component.Alert.successBorder}`,
      colorWarning: component.Alert.warningBg,
      titleTextColorWarning: component.Alert.warningText,
      contentTextColorWarning: component.Alert.warningText,
      iconColorWarning: component.Alert.warningIcon,
      borderWarning: `1px solid ${component.Alert.warningBorder}`,
      colorError: component.Alert.errorBg,
      titleTextColorError: component.Alert.errorText,
      contentTextColorError: component.Alert.errorText,
      iconColorError: component.Alert.errorIcon,
      borderError: `1px solid ${component.Alert.errorBorder}`,
    },
    Popover: {
      borderRadius: component.Popover.radius,
      color: component.Popover.bgColor,
      textColor: component.Popover.textColor,
      boxShadow: component.Popover.shadow,
      padding: component.Popover.padding,
      dividerColor: component.Popover.dividerColor,
    },
    Popconfirm: {
      iconColor: component.Dialog.iconColor,
      peers: {
        Popover: {
          borderRadius: component.Popover.radius,
          color: component.Popover.bgColor,
          textColor: component.Popover.textColor,
          boxShadow: component.Popover.shadow,
          padding: component.Popover.padding,
          dividerColor: component.Popover.dividerColor,
        },
      },
    },
    LoadingBar: {
      colorLoading: component.LoadingBar.color,
    },
  };
}
