import type { GlobalThemeOverrides } from 'naive-ui';
import type { AppearanceTokens } from './types';

export function createNaiveThemeOverrides(tokens: AppearanceTokens): GlobalThemeOverrides {
  const { semantic, component } = tokens;
  const primary = semantic.primaryColor;
  const radius = semantic.borderRadiusBase;

  return {
    common: {
      primaryColor: primary,
      primaryColorHover: semantic.primaryColorHover,
      primaryColorPressed: semantic.primaryColorPressed,
      primaryColorSuppl: semantic.primaryColorHover,
      successColor: semantic.successColor,
      warningColor: semantic.warningColor,
      errorColor: semantic.errorColor,
      infoColor: semantic.infoColor,
      textColorBase: semantic.textColorBase,
      textColor2: semantic.textColorSecondary,
      borderColor: semantic.borderColorBase,
      borderRadius: radius,
      fontFamily: semantic.fontFamilyBase,
      fontSize: semantic.fontSizeBase,
      bodyColor: semantic.pageBgColor,
      cardColor: semantic.surfaceColor,
    },
    Button: {
      borderRadiusSmall: component.Button.radius,
      borderRadiusMedium: component.Button.radius,
      borderRadiusLarge: component.Button.radius,
      heightSmall: component.Button.height,
      heightMedium: component.Button.height,
      heightLarge: component.Button.height,
      paddingMedium: `0 ${component.Button.paddingX}`,
      colorPrimary: component.Button.primaryBg,
      colorHoverPrimary: component.Button.primaryBgHover,
      colorPressedPrimary: component.Button.primaryBgPressed,
      textColorPrimary: component.Button.primaryText,
      border: `1px solid ${component.Button.borderColor}`,
    },
    Form: {
      labelTextColor: component.Form.labelTextColor,
      feedbackTextColor: component.Form.feedbackTextColor,
      feedbackHeightMedium: component.Form.itemMarginBottom,
    },
    Input: {
      borderRadius: component.Input.radius,
      heightMedium: component.Input.height,
      color: component.Input.bgColor,
      border: `1px solid ${component.Input.borderColor}`,
      borderHover: `1px solid ${component.Input.focusBorderColor}`,
      borderFocus: `1px solid ${component.Input.focusBorderColor}`,
    },
    InputNumber: {
      borderRadius: component.InputNumber.radius,
      heightMedium: component.InputNumber.height,
      color: component.InputNumber.bgColor,
      border: `1px solid ${component.InputNumber.borderColor}`,
      borderHover: `1px solid ${component.InputNumber.focusBorderColor}`,
      borderFocus: `1px solid ${component.InputNumber.focusBorderColor}`,
    },
    Select: {
      peers: {
        InternalSelection: {
          borderRadius: component.Select.radius,
          heightMedium: component.Select.height,
          color: component.Select.bgColor,
          border: `1px solid ${component.Select.borderColor}`,
          borderHover: `1px solid ${component.Select.focusBorderColor}`,
          borderActive: `1px solid ${component.Select.focusBorderColor}`,
        },
      },
    },
    Switch: {
      railColorActive: component.Switch.railColorActive,
    },
    Checkbox: {
      border: `1px solid ${component.Checkbox.borderColor}`,
      borderChecked: `1px solid ${component.Checkbox.borderColorChecked}`,
      colorChecked: component.Checkbox.borderColorChecked,
    },
    Radio: {
      dotColorActive: component.Radio.dotColorActive,
      boxShadow: `inset 0 0 0 1px ${component.Radio.borderColor}`,
      boxShadowActive: `inset 0 0 0 1px ${component.Radio.dotColorActive}`,
    },
    DataTable: {
      tdColor: component.DataTable.bodyBg,
      tdColorModal: component.DataTable.bodyBg,
      tdColorPopover: component.DataTable.bodyBg,
      thColor: component.DataTable.headerBg,
      thColorModal: component.DataTable.headerBg,
      thColorPopover: component.DataTable.headerBg,
      thTextColor: component.DataTable.thTextColor,
      tdTextColor: component.DataTable.tdTextColor,
      tdColorHover: component.DataTable.rowHoverBg,
      tdColorHoverModal: component.DataTable.rowHoverBg,
      tdColorHoverPopover: component.DataTable.rowHoverBg,
      tdColorStriped: component.DataTable.rowStripedBg,
      tdColorStripedModal: component.DataTable.rowStripedBg,
      tdColorStripedPopover: component.DataTable.rowStripedBg,
      tdColorSorting: component.DataTable.rowSortingBg,
      tdColorSortingModal: component.DataTable.rowSortingBg,
      tdColorSortingPopover: component.DataTable.rowSortingBg,
      tdColorSelected: component.DataTable.rowSelectedBg,
      tdColorSelectedModal: component.DataTable.rowSelectedBg,
      tdColorSelectedPopover: component.DataTable.rowSelectedBg,
      tdColorSelectedHover: component.DataTable.rowSelectedHoverBg,
      tdColorSelectedHoverModal: component.DataTable.rowSelectedHoverBg,
      tdColorSelectedHoverPopover: component.DataTable.rowSelectedHoverBg,
      borderColor: component.DataTable.borderColor,
      borderColorModal: component.DataTable.borderColor,
      borderColorPopover: component.DataTable.borderColor,
      thColorHover: component.DataTable.headerHoverBg,
      thColorHoverModal: component.DataTable.headerHoverBg,
      thColorHoverPopover: component.DataTable.headerHoverBg,
      thColorSorting: component.DataTable.headerHoverBg,
      thColorSortingModal: component.DataTable.headerHoverBg,
      thColorSortingPopover: component.DataTable.headerHoverBg,
      thHeightMedium: component.DataTable.thHeight,
      tdHeightMedium: component.DataTable.tdHeight,
      thPaddingMedium: `${component.DataTable.cellPaddingY} ${component.DataTable.cellPaddingX}`,
      tdPaddingMedium: `${component.DataTable.cellPaddingY} ${component.DataTable.cellPaddingX}`,
      thButtonColorHover: component.DataTable.headerHoverBg,
      thIconColor: component.DataTable.thTextColor,
      thIconColorActive: component.DataTable.selectionColor,
      loadingColor: component.DataTable.loadingColor,
    },
    Pagination: {
      itemBorderRadius: component.Pagination.itemRadius,
      itemBorderActive: `1px solid ${component.Pagination.itemColorActive}`,
      itemTextColorActive: component.Pagination.itemColorActive,
    },
    Dropdown: {
      borderRadius: component.Dropdown.radius,
      color: component.Dropdown.bgColor,
      boxShadow: component.Dropdown.shadow,
      optionColorHover: semantic.surfaceMutedColor,
    },
    Tag: {
      borderRadius: component.Tag.radius,
      color: component.Tag.primaryBg,
      textColor: component.Tag.primaryText,
      border: `1px solid ${component.Tag.borderColor}`,
    },
    Card: {
      borderRadius: component.Card.radius,
      color: component.Card.bgColor,
      borderColor: component.Card.borderColor,
      boxShadow: component.Card.shadow,
    },
    Modal: {
      borderRadius: component.Modal.radius,
      color: component.Modal.bgColor,
      boxShadow: component.Modal.shadow,
    },
    Drawer: {
      color: component.Drawer.bgColor,
      boxShadow: component.Drawer.shadow,
    },
    Menu: {
      itemHeight: component.Menu.itemHeight,
      itemTextColor: component.Menu.itemTextColor,
      itemTextColorHover: component.Menu.itemTextColor,
      itemTextColorActive: component.Menu.itemTextColorActive,
      itemTextColorActiveHover: component.Menu.itemTextColorActive,
      itemTextColorChildActive: component.Menu.itemTextColorActive,
      itemTextColorChildActiveHover: component.Menu.itemTextColorActive,
      itemIconColor: component.Menu.itemTextColor,
      itemIconColorHover: component.Menu.itemTextColor,
      itemIconColorActive: component.Menu.itemTextColorActive,
      itemIconColorActiveHover: component.Menu.itemTextColorActive,
      arrowColor: component.Menu.itemTextColor,
      arrowColorHover: component.Menu.itemTextColor,
      arrowColorActive: component.Menu.itemTextColorActive,
      arrowColorActiveHover: component.Menu.itemTextColorActive,
      itemColorActive: component.Menu.itemBgActive,
      itemColorActiveHover: component.Menu.itemBgActive,
      itemColorActiveCollapsed: component.Menu.itemBgActive,
      itemColorHover: component.Menu.itemBgHover,
      itemColorHoverInverted: component.Menu.itemBgHoverInverted,
      itemColorActiveInverted: component.Menu.itemBgActiveInverted,
      itemColorActiveHoverInverted: component.Menu.itemBgActiveInverted,
      itemColorActiveCollapsedInverted: component.Menu.itemBgActiveInverted,
      itemTextColorInverted: component.Menu.itemTextColorInverted,
      itemTextColorHoverInverted: component.Menu.itemTextColorInverted,
      itemTextColorActiveInverted: component.Menu.itemTextColorActiveInverted,
      itemTextColorActiveHoverInverted: component.Menu.itemTextColorActiveInverted,
      itemTextColorChildActiveInverted: component.Menu.itemTextColorActiveInverted,
      itemTextColorChildActiveHoverInverted: component.Menu.itemTextColorActiveInverted,
      itemIconColorInverted: component.Menu.itemTextColorInverted,
      itemIconColorHoverInverted: component.Menu.itemTextColorInverted,
      itemIconColorActiveInverted: component.Menu.itemTextColorActiveInverted,
      itemIconColorActiveHoverInverted: component.Menu.itemTextColorActiveInverted,
      itemIconColorChildActiveInverted: component.Menu.itemTextColorActiveInverted,
      itemIconColorChildActiveHoverInverted: component.Menu.itemTextColorActiveInverted,
      arrowColorInverted: component.Menu.itemTextColorInverted,
      arrowColorHoverInverted: component.Menu.itemTextColorInverted,
      arrowColorActiveInverted: component.Menu.itemTextColorActiveInverted,
      arrowColorActiveHoverInverted: component.Menu.itemTextColorActiveInverted,
      arrowColorChildActiveInverted: component.Menu.itemTextColorActiveInverted,
      arrowColorChildActiveHoverInverted: component.Menu.itemTextColorActiveInverted,
    },
    Tree: {
      nodeHeight: component.Tree.nodeHeight,
      nodeBorderRadius: component.Tree.nodeRadius,
      nodeTextColor: component.Tree.textColor,
      nodeTextColorSelected: component.Tree.textColorSelected,
      nodeTextColorDisabled: component.Tree.disabledTextColor,
      nodeColorHover: component.Tree.hoverBg,
      nodeColorSelected: component.Tree.selectedBg,
      arrowColor: component.Tree.iconColor,
      loadingColor: semantic.primaryColor,
    },
    Upload: {
      itemColorHover: component.Upload.triggerBgColor,
      itemColorHoverError: component.Upload.triggerBgColor,
      itemBorder: `1px solid ${component.Upload.itemBorderColor}`,
      itemBorderHover: `1px solid ${component.Upload.itemBorderHoverColor}`,
      itemBorderHoverError: `1px solid ${component.Upload.errorColor}`,
      itemBorderImageCard: `1px solid ${component.Upload.itemBorderColor}`,
      itemBorderImageCardHover: `1px solid ${component.Upload.itemBorderHoverColor}`,
      draggerColor: component.Upload.triggerBgColor,
      draggerBorder: `1px dashed ${component.Upload.itemBorderColor}`,
      draggerBorderHover: `1px dashed ${component.Upload.itemBorderHoverColor}`,
      draggerTextColor: component.Upload.triggerTextColor,
      draggerTextColorHover: component.Upload.triggerTextColor,
    },
    Tooltip: {
      color: component.Tooltip.bgColor,
      textColor: component.Tooltip.textColor,
    },
    LoadingBar: {
      colorLoading: component.LoadingBar.color,
    },
  };
}
